apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: niisseo-com-tls
spec:
  secretName: niisseo-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: niisseo.com
  dnsNames:
    - niisseo.com
    - www.niisseo.com
